let verbs = [
  "Build a game about",
  "Create a virtual reality app for",
  "Make a data visualization tool for",
  "Build an AI that simulates",
  "Make a quiz about",
  "Make an animation about",
  "Make 3D images that represent",
  "Develop an app about",
  "Create a social media for",
  "Create a Robot that simulates",
  "Build a puzzle about",
  "Make a math tool about",
  "Make a diagram of",
  "Create a Website about",
  "Connect",
  "Make flash cards of",
  "Build drone tools for",
  "Compare data between",
  "Classify",
  "Create graphs about",
  "Make a model of",
  "Analyze",
  "Make a chart about",
  "Control",
  "Manipulate data from",
  "Create a heat map of",
  "Build an educative app for",
  "Log activity from",
  "Create computational art about",
  "Make a timeline of",
  "Translate",
  "Make a movie about",
  "Predict",
  "Create a list for",
  "Create a bot that uses",
  "Create an extension for",
  "Create a shortcut for",
  "Develop a language for",
  "Visualize data from",
  "Simulate",
  "Create a currency for",
  "Build an algorithm for",
  "Develop a chat app for",
  "Emulate",
  "Build an API for",
  "Encrypt data from",
  "Connect",
  "Analyze",
  "Study",
  "Design Art about",
];

let nouns = [
  "dinosaurs",
  "hackathon participants",
  "children",
  "strange ideas",
  "songs",
  "students",
  "airports",
  "innovation",
  "geeks",
  "world history",
  "banks",
  "the space",
  "planets",
  "homeless people",
  "the weather",
  "anime characters",
  "leaders",
  "friends",
  "TV shows",
  "employment",
  "homework",
  "software",
  "hospitals",
  "television",
  "animals",
  "love",
  "food",
  "anxiety",
  "transportation",
  "specialists",
  "arguments",
  "news",
  "companies",
  "babies",
  "AI models",
  "programming languages",
  "stores",
  "diseases",
  "universities",
  "programmers",
  "doctors",
  "artists",
  "funding",
  "influencers",
  "bots",
  "bitcoin",
  "operating systems",
  "genes",
  "mythological characters",
  "socioeconomic data",
  "locations",
  "anatomical structures",
  "house prices",
  "random words",
  "languages",
  "animal species",
  "stock prices",
  "professions",
  "famous people",
  "historical places",
  "stars",
  "the digits of pi",
  "your Instagram feed",
  "your favorite Youtubers",
  "paintings",
  "chemical formulas",
  "natural disasters",
  "majors",
  "drinks",
  "negotiations",
  "hotels",
  "football clubs",
  "countries",
  "parking lots",
  "traffic lights",
  "parks",
  "pets",
  "recipes",
  "buildings",
  "office workers",
  "models",
  "events",
  "brainstorming",
  "cats",
  "water",
  "meditation",
  "nature",
  "donations",
  "information",
  "dating",
  "classrooms",
  "gamers",
  "health",
  "fishing",
  "activities",
  "tasks",
  "weddings",
  "wars",
  "cells",
  "clothing",
];

function changeText() {
  console.log("Clicked");
  document.getElementById("verb").innerHTML =
    verbs[Math.floor(Math.random() * verbs.length)];
  document.getElementById("noun").innerHTML =
    nouns[Math.floor(Math.random() * nouns.length)];
}
